### ISSUE TITLE
Any chance for minimap support?

### ISSUE THREAD

**Issue by byaka** [Muehe/classicdb#2]
It would be nice if cartographer of classicdb self will  shows notes on minimap, like it do Questie or Gatherer.

**Comment by Muehe** [comment]
I would like to add that one day, but no promises. It might be way too resource heavy, due to the amount of notes that would be drawn. Right now notes are only drawn on certain quest events, but to show them on the minimap they would need to be drawn during the [OnUpdate event](http://wowprogramming.com/docs/scripts/OnUpdate), which fires for every displayed frame (so 60 times in a second if you have 60 fps).

**Comment by byaka** [comment]
i think, all nearest notes of same type can be merged (while drawing) to one semi-transparent 'area'...

**Comment by Muehe** [comment]
Actually Logon and Aero started working on a similar feature for Questie, they never finished it though. Also, if you would merge the notes each time before drawing you are wasting CPU cycles, the necessary calculations can be done beforehand and saved alongside the actual coordinates for every NPC/object. Interesting algorithms would be k-means or DBSCAN.

Furthermore, this would be a lot of work to do, so do not expect it to be finished anytime soon (if at all).

**Comment by byaka** [comment]
u right, ofcourse...

**Comment by Muehe** [comment]
Oh, by the way, you can use the Cartographer extensions I added to emulate something similar to a minimap:

![minimap_example](https://cloud.githubusercontent.com/assets/8838573/26273666/85c4f29a-3d34-11e7-90b8-11d177e4543d.png)

The added commands are shown in Cartographer (there will be some more changes and fixes to them in the upcoming release):

![map_control](https://cloud.githubusercontent.com/assets/8838573/26273669/9e4d96c8-3d34-11e7-81f9-6c7ef32cd33d.png)

**Comment by byaka** [comment]
Hm, interesting...
Metamap has nice feauture -  2 separated mods, each store independent settings.
If u implement something like this with fast switching, it can be used like 1 mode for normal map and 2 mode like "minimap" emulator :)

p.s. why u select old Cartographer for map rendering, but not new Metamap?

**Comment by Muehe** [comment]
There was Metmap support in the version of WHDB shagu and I started working with, but we both decided independently to remove it from our respective projects. Adding it back in is on my road map, but priority on this is low, since I want to have all other features debugged and working with Cartographer before I do it.

Setting profiles for size and position might be relatively easy to add to Cartographer, I will look into that. Thanks for the idea.

**Comment by Muehe** [comment]
This project is not in development anymore. Take a look at [pfQuest](https://gitlab.com/shagu/pfQuest) instead, it already has minimap support.
