### ISSUE TITLE
Error in TBC client if ur ever thinking about this.

### ISSUE THREAD

**Issue by Larsy93** [Muehe/classicdb#4]
Message: Interface\AddOns\classicdb\ClassicDB_GUI.lua:603: attempt to call field 'mod' (a nil value)
Time: 06/11/17 21:02:38
Count: 1
Stack: Interface\AddOns\classicdb\ClassicDB_GUI.lua:603: in function `addLine'
Interface\AddOns\classicdb\ClassicDB_GUI.lua:646: in main chunk

ShaguDB works with the 2.4.3 client tho, its just missing the db info from the tbc areas.

**Comment by Muehe** [comment]
I played around with it a little bit and got it into a somewhat working state.

* 2.4.3 Cartographer included.
* TBC content is missing.
* Item table had to be removed because it's too big.
* Some things work, some things don't.
* Quests tracking doesn't work, but they can be marked by using the search GUI.
* There are minimap notes!

[TBC.zip](https://github.com/Muehe/classicdb/files/1069976/TBC.zip)

**Comment by Muehe** [comment]
This project is not in development anymore. If you still need a TBC addon, [pfQuest](https://gitlab.com/shagu/pfQuest) is developing one.
